CREATE TABLE events_erc721 (
    id VARCHAR(255) PRIMARY KEY,
    payload VARCHAR(255) NOT NULL,
    txHash VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL,
    collection VARCHAR(255) NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    token_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);