CREATE TABLE events (
    id VARCHAR(255) PRIMARY KEY,
    payload VARCHAR(255) NOT NULL,
    txHash VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);